export const mockDoctors = [
  {
    id: 1,
    name: "Dr. Alice Smith",
    specialty: "Cardiology",
    email: "alice.smith@healthconnect.com",
    phone: "555-1234",
    department: "Cardiology",
    experience: 10,
    available: true,
    qualification: "MD, FACC",
    consultationFee: "150.00",
    bio: "Board-certified cardiologist with 10 years of experience"
  },
  {
    id: 2,
    name: "Dr. Bob Johnson",
    specialty: "Dermatology",
    email: "bob.johnson@healthconnect.com",
    phone: "555-5678",
    department: "Dermatology",
    experience: 8,
    available: false,
    qualification: "MD, FAAD",
    consultationFee: "120.00",
    bio: "Specialized in skin disorders and cosmetic dermatology"
  },
  {
    id: 3,
    name: "Dr. Carol Lee",
    specialty: "Pediatrics",
    email: "carol.lee@healthconnect.com",
    phone: "555-8765",
    department: "Pediatrics",
    experience: 12,
    available: true,
    qualification: "MD, FAAP",
    consultationFee: "100.00",
    bio: "Dedicated to children's health and development"
  },
  {
    id: 4,
    name: "Dr. David Chen",
    specialty: "Neurology",
    email: "david.chen@healthconnect.com",
    phone: "555-4321",
    department: "Neurology",
    experience: 15,
    available: true,
    qualification: "MD, PhD",
    consultationFee: "180.00",
    bio: "Expert in neurological disorders and brain health"
  },
  {
    id: 5,
    name: "Dr. Emma Wilson",
    specialty: "Orthopedics",
    email: "emma.wilson@healthconnect.com",
    phone: "555-9876",
    department: "Orthopedics",
    experience: 9,
    available: true,
    qualification: "MD, MS Ortho",
    consultationFee: "160.00",
    bio: "Specialized in joint replacements and sports injuries"
  },
  {
    id: 6,
    name: "Dr. Frank Garcia",
    specialty: "Gynecology",
    email: "frank.garcia@healthconnect.com",
    phone: "555-2468",
    department: "Gynecology",
    experience: 11,
    available: false,
    qualification: "MD, FACOG",
    consultationFee: "140.00",
    bio: "Specialized in women's reproductive health"
  },
  {
    id: 7,
    name: "Dr. Grace Taylor",
    specialty: "Ophthalmology",
    email: "grace.taylor@healthconnect.com",
    phone: "555-1357",
    department: "Ophthalmology",
    experience: 14,
    available: true,
    qualification: "MD, FACS",
    consultationFee: "170.00",
    bio: "Expert in eye care and vision correction"
  },
  {
    id: 8,
    name: "Dr. Henry Brown",
    specialty: "Psychiatry",
    email: "henry.brown@healthconnect.com",
    phone: "555-8642",
    department: "Psychiatry",
    experience: 13,
    available: true,
    qualification: "MD, ABPN",
    consultationFee: "155.00",
    bio: "Specialized in mental health and therapy"
  },
  {
    id: 9,
    name: "Dr. Iris Davis",
    specialty: "Endocrinology",
    email: "iris.davis@healthconnect.com",
    phone: "555-7531",
    department: "Endocrinology",
    experience: 16,
    available: true,
    qualification: "MD, FACE",
    consultationFee: "175.00",
    bio: "Specialized in hormone disorders and diabetes"
  },
  {
    id: 10,
    name: "Dr. Jack Miller",
    specialty: "Urology",
    email: "jack.miller@healthconnect.com",
    phone: "555-3698",
    department: "Urology",
    experience: 17,
    available: false,
    qualification: "MD, FACS",
    consultationFee: "190.00",
    bio: "Expert in urinary tract and male reproductive health"
  }
];
